echo "Đang chuẩn bị quá trình update file lên github ....."
echo "cd /var/mobile/chonvotri.github.io/repo"
echo "git add --all"
echo "git commit -m "Init commit""
echo "git push -u origin main"
echo "27th5"
echo "ghp_g6DFVfAwsTtqFdYRSYpQUghm0u5Tc20JlC6"
echo "xong!"
echo " Make by QUANGMINH!"
exit 0
